---
repo_name: SpaceVim
repo_url: https://github.com/wenijinew/SpaceVim.git
edit_uri: edit/master/docs/

site_name: SpaceVim Docs
nav:
  - Home:
      - index.md
  - Quick Start:
      - quick-start-guide.md
  - Documentation:
      - documentation.md
  - Development:
      - development.md
  - Community:
      - community.md
  - Sponsors:
      - sponsors.md
  - About:
      - about.md

extra_css:
  - css/extra.css

extra:
  tags:
    diary: work

theme:
  logo: logo.png
  font:
    text: "Roboto"
    code: "Roboto Mono"
  name: material
  custom_dir: docs/overrides
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.code.expand
    - content.footnote.tooltips
    - navigation.expand
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - toc.follow
    - announce.dismiss
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    tag:
      work: fontawesome/solid/pen-nib
    edit: material/pencil
    view: material/eye

plugins:
  - search
  - mkdocstrings
  - tags
  - include-markdown

markdown_extensions:
  - abbr
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - attr_list
